In [9]:
import numpy as np
import pandas as pd

In [5]:
np.__version__

'1.16.4'

In [6]:
a=np.array([1,2,3,4,5,6,7,8,9])

In [7]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.full((3,3),True,dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [13]:
a[a%2==1]

array([1, 3, 5, 7, 9])

In [14]:
a[a%2==1]=-1

In [15]:
a

array([-1,  2, -1,  4, -1,  6, -1,  8, -1])

In [21]:
b=np.arange(10)

In [22]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
out=np.where(b%2==1,-1,b)

In [24]:
out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [27]:
print(b)
print(out)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [39]:
c=np.arange(10).reshape(2,-1)

In [40]:
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [41]:
d=np.repeat(1,10).reshape(2,-1)

In [42]:
d

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [44]:
np.vstack([c,d])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [45]:
np.hstack([c,d])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [46]:
np.concatenate([c,d],axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [47]:
np.concatenate([c,d],axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [48]:
e=np.array([1,2,3])

In [53]:
np.r_[np.repeat(e,3),np.tile(e,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [54]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [66]:
np.intersect1d(a,b)

array([2, 4])

In [69]:
np.setdiff1d(a,b)

array([1, 3, 5, 6])

In [70]:
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

In [71]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [74]:
a[(a>=5)&(a<=10)]

array([ 6,  9, 10])

In [75]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

In [91]:
arr = np.arange(9).reshape(3,3)

In [77]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [85]:
arr[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [88]:
arr[:,[0,2,1]]

array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

In [90]:
arr[[1,2,0],:]

array([[3, 4, 5],
       [6, 7, 8],
       [0, 1, 2]])

In [92]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [93]:
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [94]:
arr[::1]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [96]:
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [107]:
np.random.uniform(5,10,size=(5,3))

array([[9.78566554, 7.43735049, 9.61181271],
       [9.7226305 , 9.47095123, 7.82240529],
       [8.26392331, 9.63854144, 5.08236734],
       [7.5407144 , 7.4393634 , 7.80595809],
       [7.26392474, 9.91825475, 7.23230579]])

In [117]:
rand_arr = np.random.random([5,3])

In [118]:
np.set_printoptions(precision=3)

In [120]:
rand_arr[:4]

array([[0.107, 0.267, 0.723],
       [0.774, 0.194, 0.05 ],
       [0.518, 0.547, 0.708],
       [0.865, 0.199, 0.29 ]])

In [129]:
np.random.seed(100)

In [123]:
np.random.random([3,3])/1e3

array([[5.434e-04, 2.784e-04, 4.245e-04],
       [8.448e-04, 4.719e-06, 1.216e-04],
       [6.707e-04, 8.259e-04, 1.367e-04]])

In [131]:
np.set_printoptions(suppress=True,precision=6)

In [132]:
np.random.random([3,3])/1e3

array([[0.000575, 0.000891, 0.000209],
       [0.000185, 0.000108, 0.00022 ],
       [0.000979, 0.000812, 0.000172]])

In [134]:
a=np.arange(15)

In [135]:
np.set_printoptions(threshold=6)

In [136]:
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [142]:
np.set_printoptions(threshold=100)

In [143]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
iris = np.genfromtxt("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data", delimiter=',', dtype='object')

In [10]:
pd.DataFrame(iris)

0       1       2       3                  4
0    b'5.1'  b'3.5'  b'1.4'  b'0.2'     b'Iris-setosa'
1    b'4.9'  b'3.0'  b'1.4'  b'0.2'     b'Iris-setosa'
2    b'4.7'  b'3.2'  b'1.3'  b'0.2'     b'Iris-setosa'
3    b'4.6'  b'3.1'  b'1.5'  b'0.2'     b'Iris-setosa'
4    b'5.0'  b'3.6'  b'1.4'  b'0.2'     b'Iris-setosa'
5    b'5.4'  b'3.9'  b'1.7'  b'0.4'     b'Iris-setosa'
6    b'4.6'  b'3.4'  b'1.4'  b'0.3'     b'Iris-setosa'
7    b'5.0'  b'3.4'  b'1.5'  b'0.2'     b'Iris-setosa'
8    b'4.4'  b'2.9'  b'1.4'  b'0.2'     b'Iris-setosa'
9    b'4.9'  b'3.1'  b'1.5'  b'0.1'     b'Iris-setosa'
10   b'5.4'  b'3.7'  b'1.5'  b'0.2'     b'Iris-setosa'
11   b'4.8'  b'3.4'  b'1.6'  b'0.2'     b'Iris-setosa'
12   b'4.8'  b'3.0'  b'1.4'  b'0.1'     b'Iris-setosa'
13   b'4.3'  b'3.0'  b'1.1'  b'0.1'     b'Iris-setosa'
14   b'5.8'  b'4.0'  b'1.2'  b'0.2'     b'Iris-setosa'
15   b'5.7'  b'4.4'  b'1.5'  b'0.4'     b'Iris-setosa'
16   b'5.4'  b'3.9'  b'1.3'  b'0.4'     b'Iris-setosa'
17   b'5.1'  b'3.5'  b'1.4'  b'0.3'     b'Iris-setosa'
18   b'5.7'  b'3.8'  b'1.7'  b'0.3'     b'Iris-setosa'
19   b'5.1'  b'3.8'  b'1.5'  b'0.3'     b'Iris-setosa'
20   b'5.4'  b'3.4'  b'1.7'  b'0.2'     b'Iris-setosa'
21   b'5.1'  b'3.7'  b'1.5'  b'0.4'     b'Iris-setosa'
22   b'4.6'  b'3.6'  b'1.0'  b'0.2'     b'Iris-setosa'
23   b'5.1'  b'3.3'  b'1.7'  b'0.5'     b'Iris-setosa'
24   b'4.8'  b'3.4'  b'1.9'  b'0.2'     b'Iris-setosa'
25   b'5.0'  b'3.0'  b'1.6'  b'0.2'     b'Iris-setosa'
26   b'5.0'  b'3.4'  b'1.6'  b'0.4'     b'Iris-setosa'
27   b'5.2'  b'3.5'  b'1.5'  b'0.2'     b'Iris-setosa'
28   b'5.2'  b'3.4'  b'1.4'  b'0.2'     b'Iris-setosa'
29   b'4.7'  b'3.2'  b'1.6'  b'0.2'     b'Iris-setosa'
..      ...     ...     ...     ...                ...
120  b'6.9'  b'3.2'  b'5.7'  b'2.3'  b'Iris-virginica'
121  b'5.6'  b'2.8'  b'4.9'  b'2.0'  b'Iris-virginica'
122  b'7.7'  b'2.8'  b'6.7'  b'2.0'  b'Iris-virginica'
123  b'6.3'  b'2.7'  b'4.9'  b'1.8'  b'Iris-virginica'
124  b'6.7'  b'3.3'  b'5.7'  b'2.1'  b'Iris-virginica'
125  b'7.2'  b'3.2'  b'6.0'  b'1.8'  b'Iris-virginica'
126  b'6.2'  b'2.8'  b'4.8'  b'1.8'  b'Iris-virginica'
127  b'6.1'  b'3.0'  b'4.9'  b'1.8'  b'Iris-virginica'
128  b'6.4'  b'2.8'  b'5.6'  b'2.1'  b'Iris-virginica'
129  b'7.2'  b'3.0'  b'5.8'  b'1.6'  b'Iris-virginica'
130  b'7.4'  b'2.8'  b'6.1'  b'1.9'  b'Iris-virginica'
131  b'7.9'  b'3.8'  b'6.4'  b'2.0'  b'Iris-virginica'
132  b'6.4'  b'2.8'  b'5.6'  b'2.2'  b'Iris-virginica'
133  b'6.3'  b'2.8'  b'5.1'  b'1.5'  b'Iris-virginica'
134  b'6.1'  b'2.6'  b'5.6'  b'1.4'  b'Iris-virginica'
135  b'7.7'  b'3.0'  b'6.1'  b'2.3'  b'Iris-virginica'
136  b'6.3'  b'3.4'  b'5.6'  b'2.4'  b'Iris-virginica'
137  b'6.4'  b'3.1'  b'5.5'  b'1.8'  b'Iris-virginica'
138  b'6.0'  b'3.0'  b'4.8'  b'1.8'  b'Iris-virginica'
139  b'6.9'  b'3.1'  b'5.4'  b'2.1'  b'Iris-virginica'
140  b'6.7'  b'3.1'  b'5.6'  b'2.4'  b'Iris-virginica'
141  b'6.9'  b'3.1'  b'5.1'  b'2.3'  b'Iris-virginica'
142  b'5.8'  b'2.7'  b'5.1'  b'1.9'  b'Iris-virginica'
143  b'6.8'  b'3.2'  b'5.9'  b'2.3'  b'Iris-virginica'
144  b'6.7'  b'3.3'  b'5.7'  b'2.5'  b'Iris-virginica'
145  b'6.7'  b'3.0'  b'5.2'  b'2.3'  b'Iris-virginica'
146  b'6.3'  b'2.5'  b'5.0'  b'1.9'  b'Iris-virginica'
147  b'6.5'  b'3.0'  b'5.2'  b'2.0'  b'Iris-virginica'
148  b'6.2'  b'3.4'  b'5.4'  b'2.3'  b'Iris-virginica'
149  b'5.9'  b'3.0'  b'5.1'  b'1.8'  b'Iris-virginica'

[150 rows x 5 columns]

In [8]:
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

In [13]:
iris.shape

(150, 5)

In [14]:
species=np.array([row[4] for row in iris])

In [16]:
species[:5]

array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa'], dtype='|S15')

In [18]:
iris_2d=np.array([row.tolist()[:4] for row in iris])

In [20]:
iris_2d[:4]

array([[b'5.1', b'3.5', b'1.4', b'0.2'],
       [b'4.9', b'3.0', b'1.4', b'0.2'],
       [b'4.7', b'3.2', b'1.3', b'0.2'],
       [b'4.6', b'3.1', b'1.5', b'0.2']], dtype='|S3')

In [31]:
sepallength=np.genfromtxt("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data",delimiter=',',dtype='float',usecols=[0])

In [32]:
mean,median,std=np.mean(sepallength),np.median(sepallength),np.std(sepallength)

In [33]:
print(mean,median,std)

5.843333333333334 5.8 0.8253012917851409


In [35]:
max,min=sepallength.max(),sepallength.min()

In [36]:
S=sepallength-min/max-min

In [41]:
S

array([ 0.2556962,  0.0556962, -0.1443038, -0.2443038,  0.1556962,
        0.5556962, -0.2443038,  0.1556962, -0.4443038,  0.0556962,
        0.5556962, -0.0443038, -0.0443038, -0.5443038,  0.9556962,
        0.8556962,  0.5556962,  0.2556962,  0.8556962,  0.2556962,
        0.5556962,  0.2556962, -0.2443038,  0.2556962, -0.0443038,
        0.1556962,  0.1556962,  0.3556962,  0.3556962, -0.1443038,
       -0.0443038,  0.5556962,  0.3556962,  0.6556962,  0.0556962,
        0.1556962,  0.6556962,  0.0556962, -0.4443038,  0.2556962,
        0.1556962, -0.3443038, -0.4443038,  0.1556962,  0.2556962,
       -0.0443038,  0.2556962, -0.2443038,  0.4556962,  0.1556962,
        2.1556962,  1.5556962,  2.0556962,  0.6556962,  1.6556962,
        0.8556962,  1.4556962,  0.0556962,  1.7556962,  0.3556962,
        0.1556962,  1.0556962,  1.1556962,  1.2556962,  0.7556962,
        1.8556962,  0.7556962,  0.9556962,  1.3556962,  0.7556962,
        1.0556962,  1.2556962,  1.4556962,  1.2556962,  1.5556

In [42]:
def softmax(x):
    e_x=np.exp(x-x.max())
    return e_x/e_x.sum(axis=0)
    

In [44]:
softmax(sepallength)

array([0.00221959, 0.00181724, 0.00148783, 0.00134625, 0.00200836,
       0.00299613, 0.00134625, 0.00200836, 0.00110221, 0.00181724,
       0.00299613, 0.00164431, 0.00164431, 0.00099732, 0.0044697 ,
       0.00404435, 0.00299613, 0.00221959, 0.00404435, 0.00221959,
       0.00299613, 0.00221959, 0.00134625, 0.00221959, 0.00164431,
       0.00200836, 0.00200836, 0.00245302, 0.00245302, 0.00148783,
       0.00164431, 0.00299613, 0.00245302, 0.00331123, 0.00181724,
       0.00200836, 0.00331123, 0.00181724, 0.00110221, 0.00221959,
       0.00200836, 0.00121813, 0.00110221, 0.00200836, 0.00221959,
       0.00164431, 0.00221959, 0.00134625, 0.00271101, 0.00200836,
       0.01483991, 0.00814432, 0.01342771, 0.00331123, 0.00900086,
       0.00404435, 0.00736928, 0.00181724, 0.00994749, 0.00245302,
       0.00200836, 0.00493978, 0.0054593 , 0.00603346, 0.00365948,
       0.01099368, 0.00365948, 0.0044697 , 0.006668  , 0.00365948,
       0.00493978, 0.00603346, 0.00736928, 0.00603346, 0.00814

In [46]:
np.percentile(sepallength,[5,95])

array([4.6  , 7.255])

In [47]:
np.random.seed(100)

In [48]:
i,j=np.where(iris_2d)

In [50]:
iris_2d[np.random.choice((i),20),np.random.choice((j),20)]=np.nan

In [52]:
iris_2d

array([[b'5.1', b'3.5', b'1.4', b'0.2'],
       [b'nan', b'3.0', b'1.4', b'0.2'],
       [b'4.7', b'3.2', b'1.3', b'0.2'],
       [b'4.6', b'3.1', b'1.5', b'0.2'],
       [b'5.0', b'3.6', b'1.4', b'0.2'],
       [b'5.4', b'3.9', b'1.7', b'0.4'],
       [b'4.6', b'3.4', b'1.4', b'0.3'],
       [b'5.0', b'3.4', b'1.5', b'0.2'],
       [b'4.4', b'2.9', b'1.4', b'0.2'],
       [b'4.9', b'3.1', b'1.5', b'0.1'],
       [b'5.4', b'3.7', b'1.5', b'0.2'],
       [b'4.8', b'3.4', b'1.6', b'0.2'],
       [b'4.8', b'3.0', b'nan', b'0.1'],
       [b'4.3', b'3.0', b'nan', b'0.1'],
       [b'5.8', b'4.0', b'1.2', b'0.2'],
       [b'5.7', b'4.4', b'1.5', b'0.4'],
       [b'5.4', b'3.9', b'1.3', b'0.4'],
       [b'5.1', b'3.5', b'1.4', b'0.3'],
       [b'5.7', b'3.8', b'1.7', b'0.3'],
       [b'nan', b'3.8', b'1.5', b'0.3'],
       [b'5.4', b'3.4', b'1.7', b'0.2'],
       [b'5.1', b'3.7', b'nan', b'0.4'],
       [b'4.6', b'3.6', b'1.0', b'0.2'],
       [b'nan', b'3.3', b'1.7', b'0.5'],
       [b'4.8', 

In [70]:
iris_2d = np.genfromtxt("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data", delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

In [64]:
print("Number=",np.isnan(iris_2d[:,0]).sum())
print("Where=",np.where(np.isnan(iris_2d[:,0])))

Number= 4
Where= (array([  0,  71,  84, 138], dtype=int64),)


In [66]:
iris_2d = np.genfromtxt("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data", delimiter=',', dtype='float', usecols=[0,1,2,3])

In [68]:
cond=(iris_2d[:,2]>1.5) & (iris_2d[:,0]<5.0)

In [69]:
iris_2d[cond]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

In [71]:
condt=iris_2d[:,:]!=np.nan

In [74]:
nan_row=np.array([~np.any(np.isnan(row)) for row in iris_2d])

In [76]:
iris_2d[nan_row][:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [77]:
iris = np.genfromtxt("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data", delimiter=',', dtype='float', usecols=[0,1,2,3])


In [82]:
from scipy.stats.stats import pearsonr

In [84]:
corr,pvalue=pearsonr(iris[:,0],iris[:,2])

In [85]:
corr

0.8717541573048712

In [86]:
pvalue

1.0384540627941809e-47

In [88]:
np.isnan(iris_2d).any()

True

In [95]:
nan_row=([np.any(np.isnan(iris_2d)) for row in iris_2d])

In [97]:
iris_2d[np.isnan(iris_2d)]=0

In [101]:
iris_2d[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [0. , 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [0. , 3.1, 1.5, 0.1]])

In [114]:
iris=np.genfromtxt("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data", delimiter=',', dtype='object')

In [115]:
species=np.array([row.tolist()[4] for row in iris])

In [116]:
np.unique(species,return_counts=True)

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
       dtype='|S15'), array([50, 50, 50], dtype=int64))

In [117]:
petal_length_bin = np.digitize(iris[:, 2].astype('float'), [0, 3, 5, 10])


In [118]:
petal_length_bin

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 2, 3, 3, 2, 2, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3], dtype=int64)

In [121]:
label_map={1:'Small',2:'Medium',3:'Large',4:np.nan}

In [123]:
petal_length_cat = [label_map[x] for x in petal_length_bin]


In [125]:
petal_length_cat

['Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Small',
 'Medium',
 'Medium',
 'Medium',
 'Medium',
 'Medium',
 'Medium',
 'Medium',
 'Medium',
 'Medium',
 'Medium',
 'Medium',
 'Medium',
 'Medium',
 'Medium',
 'Medium',
 'Medium',
 'Medium',
 'Medium',
 'Medium',
 'Medium',
 'Medium',
 'Medium',
 'Medium',
 'Medium',
 'Medium',
 'Medium',
 'Medium',
 'Large',
 'Medium',
 'Medium',
 'Medium',
 'Medium',
 'Medium',
 'Large',
 'Medium',
 'Medium',
 'Medium',
 'Medium',
 'Medium',
 'Medium',
 'Medium',
 'Medium',
 'Medium',
 'Medium',
 'Medium',
 'Mediu

In [1]:
iris.head()

NameError: name 'iris' is not defined